# Generated by Django 3.2.4 on 2021-06-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='PersonActive',
        ),
    ]
