# Generated by Django 3.2.4 on 2021-06-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0002_remove_customusers_personactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='username',
        ),
        migrations.AddField(
            model_name='customusers',
            name='PersonDirectSuperer',
            field=models.IntegerField(default=2019214288),
            preserve_default=False,
        ),
    ]
