# Generated by Django 3.2.4 on 2021-06-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0003_auto_20210626_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusers',
            old_name='PersonDirectSuperer',
            new_name='PersonDirectSuperior',
        ),
    ]
