# Generated by Django 3.2.4 on 2021-06-26 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0004_rename_persondirectsuperer_customusers_persondirectsuperior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='PersonGender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male')]),
        ),
        migrations.CreateModel(
            name='ProcessRaiseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcessRaiseTime', models.TimeField(auto_now_add=True)),
                ('ProcessRaiseInfo', models.JSONField()),
                ('ProcessRaiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'processraiseevent',
                'verbose_name_plural': 'processraiseevents',
            },
        ),
        migrations.CreateModel(
            name='ProcessHandleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcessHandleLevel', models.IntegerField()),
                ('ProcessHandleTime', models.TimeField(auto_now=True)),
                ('ProcessHandleStatus', models.IntegerField(choices=[(1, 'Unhandled'), (2, 'WaitingToBeHandled'), (3, 'Handled')])),
                ('ProcessHandleInfo', models.JSONField()),
                ('ProcessHandleResult', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Revert')])),
                ('ProcessHandler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ProcessOriginalEvent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oa.processraiseevent')),
            ],
            options={
                'verbose_name': 'ProcessHandleEvent',
                'verbose_name_plural': 'ProcessHandleEvents',
            },
        ),
    ]
