# Generated by Django 3.2.4 on 2021-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0006_alter_customusers_persondirectsuperior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhandleevent',
            name='ProcessHandleTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processraiseevent',
            name='ProcessRaiseTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
