# Generated by Django 3.2.4 on 2021-06-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0007_auto_20210626_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='PersonDirectSuperior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
