# Generated by Django 3.2.4 on 2021-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0008_alter_customusers_persondirectsuperior'),
    ]

    operations = [
        migrations.AddField(
            model_name='processraiseevent',
            name='ProcessRaiseStatus',
            field=models.IntegerField(choices=[(1, 'Unhandled'), (2, 'Handling'), (3, 'HandledAndAccepted'), (4, 'HandledAndRejected')], default=1),
        ),
    ]
