# Generated by Django 3.2.4 on 2021-06-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0009_processraiseevent_processraisestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processhandleevent',
            name='ProcessHandleInfo',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='processhandleevent',
            name='ProcessHandleResult',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Revert')], null=True),
        ),
    ]
