# Generated by Django 3.2.4 on 2021-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0010_auto_20210626_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processraiseevent',
            name='ProcessRaiseStatus',
            field=models.IntegerField(choices=[(1, 'Unhandled'), (2, 'Handling'), (3, 'HandledAndAccepted'), (4, 'HandledAndRejected'), (5, 'WaittingToBeModified')], default=1),
        ),
    ]
