# Generated by Django 3.2.4 on 2021-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0011_alter_processraiseevent_processraisestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='PersonFirstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='PersonLastName',
            field=models.CharField(max_length=50),
        ),
    ]
