# Generated by Django 3.2.4 on 2021-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0012_auto_20210628_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='processraiseevent',
            name='ProcessRaiseTitle',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
