# Generated by Django 3.2.4 on 2021-06-28 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0013_processraiseevent_processraisetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeRaiseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeRaiseTime', models.DateTimeField(auto_now_add=True)),
                ('NoticeRaiseTitle', models.CharField(max_length=50)),
                ('NoticeRaiseInfo', models.JSONField()),
                ('NoticeRaiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NoticeRaiseEvent',
                'verbose_name_plural': 'NoticeRaiseEvents',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NoticeReceiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NeedToRelay', models.BooleanField(default=False)),
                ('NoticeRelay', models.BooleanField(default=False)),
                ('NoticeRead', models.BooleanField(default=False)),
                ('NoticeOriginalEvent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oa.noticeraiseevent')),
                ('NoticeReceiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NoticeReceiveEvent',
                'verbose_name_plural': 'NoticeReceiveEvents',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
