# Generated by Django 3.2.4 on 2021-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0014_noticeraiseevent_noticereceiveevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeraiseevent',
            name='NoticeRaiseTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processraiseevent',
            name='ProcessRaiseTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
