swagger: '2.0'
info:
  title: OA API
  description: OA description
  version: v1
host: 'dev.yilantingfeng.site'
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []

paths:
  /addUser/:
    post:
      operationId: 添加用户
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/CustomUserAdd'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CustomUserAdd'
      tags:
        - 添加用户
    parameters: []
  /createProcess/:
    post:
      operationId: 发起审批流程
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateProcess'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CreateProcess'
      tags:
        - 发起审批流程
    parameters: []
  /filterUsers/:
    get:
      operationId: 过滤下级用户
      description: ''
      parameters:
        - name: search
          in: query
          description: A search term.
          required: false
          type: string
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/CustomUserDetailSerializerForGet'
      tags:
        - 过滤下级用户
    parameters: []
  '/handleProcess/{ProcessOriginalEvent}/':
    get:
      operationId: 处理流程——获取当级信息
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/HandleProcessSerializerForGet'
      tags:
        - 处理流程
    put:
      operationId: 处理流程——更新当级信息
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/HandleProcessSerializerForPut'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/HandleProcessSerializerForPut'
      tags:
        - 处理流程
    # patch:
    #   operationId: handleProcess_partial_update
    #   description: ''
    #   parameters:
    #     - name: data
    #       in: body
    #       required: true
    #       schema:
    #         $ref: '#/definitions/HandleProcessSerializerForGet'
    #   responses:
    #     '200':
    #       description: ''
    #       schema:
    #         $ref: '#/definitions/HandleProcessSerializerForGet'
    #   tags:
    #     - 处理流程
    parameters:
      - name: ProcessOriginalEvent
        in: path
        required: true
        type: string
  /listProcesses/:
    get:
      operationId: 获取发起流程
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/ListProcess'
      tags:
        - 获取发起流程
    parameters: []
  /listUnhandledProcess/:
    get:
      operationId: 获取未处理流程列表
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/ListUnhandledProcess'
      tags:
        - 获取未处理流程列表
    parameters: []
  /listUsers/:
    get:
      operationId: 获取用户列表
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/CustomUserAll'
      tags:
        - 获取用户列表
    parameters: []
  '/modifyProcessRaiseEvent/{id}/':
    get:
      operationId: 修改流程发起信息——获取信息
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ModifyProcessRaiseEventSerializerForGet'
      tags:
        - 修改流程发起信息
    put:
      operationId: 修改流程发起信息——更新信息
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/ModifyProcessRaiseEventSerializerForPut'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ModifyProcessRaiseEventSerializerForPut'
      tags:
        - 修改流程发起信息
    # patch:
    #   operationId: modifyProcessRaiseEvent_partial_update
    #   description: ''
    #   parameters:
    #     - name: data
    #       in: body
    #       required: true
    #       schema:
    #         $ref: '#/definitions/ModifyProcessRaiseEventSerializerForGet'
    #   responses:
    #     '200':
    #       description: ''
    #       schema:
    #         $ref: '#/definitions/ModifyProcessRaiseEventSerializerForGet'
    #   tags:
    #     - modifyProcessRaiseEvent
    parameters:
      - name: id
        in: path
        required: true
        type: string
  '/processDetail/{id}/':
    get:
      operationId: 获取流程详细流转信息
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - 获取流程详细流转信息
    parameters:
      - name: id
        in: path
        required: true
        type: string
  '/userDetail/{id}/':
    get:
      operationId: 用户详细信息——获取信息
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CustomUserDetailSerializerForGet'
      tags:
        - 用户详细信息
    put:
      operationId: 用户详细信息——更新信息
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - 用户详细信息
    # patch:
    #   operationId: userDetail_partial_update
    #   description: ''
    #   parameters:
    #     - name: data
    #       in: body
    #       required: true
    #       schema:
    #         $ref: '#/definitions/CustomUserDetailSerializerForGet'
    #   responses:
    #     '200':
    #       description: ''
    #       schema:
    #         $ref: '#/definitions/CustomUserDetailSerializerForGet'
    #   tags:
    #     - userDetail
    parameters:
      - name: id
        in: path
        required: true
        type: string
definitions:
  CustomUserAdd:
    description: >-
      CustomUsers(password, last_login, is_superuser, is_staff, is_active,
      PersonNo, PersonEmail, PersonLastName, PersonFirstName, PersonGender,
      PersonAge, PersonPhone, PersonJob, PersonDirectSuperior)
    required:
      - PersonNo
      - password
      - password_confirm
      - PersonEmail
      - PersonLastName
      - PersonFirstName
      - PersonGender
      - PersonAge
      - PersonPhone
      - PersonJob
      - PersonDirectSuperior
    type: object
    properties:
      PersonNo:
        title: PersonNo
        type: integer
        maximum: 2147483647
        minimum: -2147483648
      password:
        title: Password
        type: string
        maxLength: 128
        minLength: 1
      password_confirm:
        title: Password confirm
        type: string
        minLength: 1
      PersonEmail:
        title: PersonEmail
        type: string
        format: email
        maxLength: 254
        minLength: 1
      PersonLastName:
        title: 姓
        type: string
        maxLength: 50
        minLength: 1
      PersonFirstName:
        title: 名
        type: string
        maxLength: 50
        minLength: 1
      PersonGender:
        title: PersonGender
        type: integer
        enum:
          - 1
          - 2
      PersonAge:
        title: PersonAge
        type: integer
        maximum: 2147483647
        minimum: -2147483648
      PersonPhone:
        title: PersonPhone
        type: string
        maxLength: 11
        minLength: 1
      PersonJob:
        title: PersonJob
        type: string
        maxLength: 50
        minLength: 1
      PersonDirectSuperior:
        title: PersonDirectSuperior
        type: integer
      is_superuser:
        title: Superuser status
        description: >-
          Designates that this user has all permissions without explicitly
          assigning them.
        type: boolean
      is_staff:
        title: Staff status
        description: Designates whether the user can log into this admin site.
        type: boolean
      is_active:
        title: Active
        description: >-
          Designates whether this user should be treated as active. Unselect
          this instead of deleting accounts.
        type: boolean
  CreateProcess:
    description: >-
      ProcessRaiseEvent(id, ProcessRaiser, ProcessRaiseTime, ProcessRaiseInfo,
      ProcessRaiseStatus)
    required:
      - ProcessRaiseInfo
      - CreateProcessSteps
    type: object
    properties:
      ProcessRaiseInfo:
        title: ProcessRaiseInfo
        type: object
      CreateProcessSteps:
        title: Createprocesssteps
        type: object
  CustomUserDetailSerializerForGet:
    description: >-
      CustomUsers(password, last_login, is_superuser, is_staff, is_active,
      PersonNo, PersonEmail, PersonLastName, PersonFirstName, PersonGender,
      PersonAge, PersonPhone, PersonJob, PersonDirectSuperior)
    required:
      - PersonNo
      - PersonEmail
      - PersonLastName
      - PersonFirstName
      - PersonGender
      - PersonAge
      - PersonPhone
      - PersonJob
      - PersonDirectSuperior
    type: object
    properties:
      PersonNo:
        title: PersonNo
        type: integer
        maximum: 2147483647
        minimum: -2147483648
      last_login:
        title: Last login
        type: string
        format: date-time
        x-nullable: true
      is_superuser:
        title: Superuser status
        description: >-
          Designates that this user has all permissions without explicitly
          assigning them.
        type: boolean
      is_staff:
        title: Staff status
        description: Designates whether the user can log into this admin site.
        type: boolean
      is_active:
        title: Active
        description: >-
          Designates whether this user should be treated as active. Unselect
          this instead of deleting accounts.
        type: boolean
      PersonEmail:
        title: PersonEmail
        type: string
        format: email
        maxLength: 254
        minLength: 1
      PersonLastName:
        title: 姓
        type: string
        maxLength: 50
        minLength: 1
      PersonFirstName:
        title: 名
        type: string
        maxLength: 50
        minLength: 1
      PersonGender:
        title: PersonGender
        type: integer
        enum:
          - 1
          - 2
      PersonAge:
        title: PersonAge
        type: integer
        maximum: 2147483647
        minimum: -2147483648
      PersonPhone:
        title: PersonPhone
        type: string
        maxLength: 11
        minLength: 1
      PersonJob:
        title: PersonJob
        type: string
        maxLength: 50
        minLength: 1
      PersonDirectSuperior:
        title: PersonDirectSuperior
        type: integer
  HandleProcessSerializerForGet:
    description: >-
      ProcessHandleEvent(id, ProcessOriginalEvent, ProcessHandleLevel,
      ProcessHandleTime, ProcessHandleStatus, ProcessHandler, ProcessHandleInfo,
      ProcessHandleResult)
    required:
      - ProcessOriginalEvent
      - ProcessHandler
      - ProcessHandleLevel
      - ProcessHandleStatus
    type: object
    properties:
      ProcessOriginalEvent:
        title: ProcessOriginalEvent
        type: integer
      ProcessHandler:
        title: ProcessHandler
        type: integer
      ProcessHandleLevel:
        title: ProcessHandleLevel
        type: integer
        maximum: 2147483647
        minimum: -2147483648
      ProcessHandleInfo:
        title: ProcessHandleInfo
        type: object
        x-nullable: true
      ProcessHandleResult:
        title: ProcessHandleResult
        type: integer
        enum:
          - 1
          - 2
          - 3
        x-nullable: true
      ProcessHandleStatus:
        title: ProcessHandleStatus
        type: integer
        enum:
          - 1
          - 2
          - 3
  HandleProcessSerializerForPut:
    description: >-
      ProcessHandleEvent(id, ProcessOriginalEvent, ProcessHandleLevel,
      ProcessHandleTime, ProcessHandleStatus, ProcessHandler, ProcessHandleInfo,
      ProcessHandleResult)
    type: object
    properties:
      ProcessHandleInfo:
        title: ProcessHandleInfo
        type: object
        x-nullable: true
      ProcessHandleResult:
        title: ProcessHandleResult
        type: integer
        enum:
          - 1
          - 2
          - 3
        x-nullable: true
  ListProcess:
    description: >-
      ProcessRaiseEvent(id, ProcessRaiser, ProcessRaiseTime, ProcessRaiseInfo,
      ProcessRaiseStatus)
    required:
      - ProcessRaiser
      - ProcessRaiseInfo
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      ProcessRaiser:
        title: ProcessRaiser
        type: integer
      ProcessRaiseTime:
        title: ProcessRaiseTime
        type: string
        format: date-time
        readOnly: true
      ProcessRaiseInfo:
        title: ProcessRaiseInfo
        type: object
      ProcessRaiseStatus:
        title: ProcessRaiseStatus
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
  ListUnhandledProcess:
    description: >-
      ProcessRaiseEvent(id, ProcessRaiser, ProcessRaiseTime, ProcessRaiseInfo,
      ProcessRaiseStatus)
    required:
      - ProcessRaiser
      - ProcessRaiseInfo
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      ProcessRaiser:
        title: ProcessRaiser
        type: integer
      ProcessRaiseTime:
        title: ProcessRaiseTime
        type: string
        format: date-time
        readOnly: true
      ProcessRaiseInfo:
        title: ProcessRaiseInfo
        type: object
      ProcessRaiseStatus:
        title: ProcessRaiseStatus
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
  CustomUserAll:
    description: >-
      CustomUsers(password, last_login, is_superuser, is_staff, is_active,
      PersonNo, PersonEmail, PersonLastName, PersonFirstName, PersonGender,
      PersonAge, PersonPhone, PersonJob, PersonDirectSuperior)
    required:
      - PersonNo
      - PersonLastName
      - PersonFirstName
    type: object
    properties:
      PersonNo:
        title: PersonNo
        type: integer
        maximum: 2147483647
        minimum: -2147483648
      PersonLastName:
        title: 姓
        type: string
        maxLength: 50
        minLength: 1
      PersonFirstName:
        title: 名
        type: string
        maxLength: 50
        minLength: 1
  ModifyProcessRaiseEventSerializerForGet:
    description: >-
      ProcessRaiseEvent(id, ProcessRaiser, ProcessRaiseTime, ProcessRaiseInfo,
      ProcessRaiseStatus)
    required:
      - ProcessRaiseInfo
      - ProcessRaiser
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      ProcessRaiseTime:
        title: ProcessRaiseTime
        type: string
        format: date-time
        readOnly: true
      ProcessRaiseInfo:
        title: ProcessRaiseInfo
        type: object
      ProcessRaiseStatus:
        title: ProcessRaiseStatus
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
      ProcessRaiser:
        title: ProcessRaiser
        type: integer
  ModifyProcessRaiseEventSerializerForPut:
    description: >-
      ProcessRaiseEvent(id, ProcessRaiser, ProcessRaiseTime, ProcessRaiseInfo,
      ProcessRaiseStatus)
    required:
      - ProcessRaiseInfo
    type: object
    properties:
      ProcessRaiseInfo:
        title: ProcessRaiseInfo
        type: object
